service: auction-service

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - ${file(./iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}

functions:
  hello: # function
    handler: handler.hello
    description: "hello method"
    events: # events that trigger this action
      - http: # creates an API gateway endpoint
          method: GET
          path: /auction/hello
  createAuction: #function
    handler: handler.createAuction
    description: "Creates an auction"
    events: # events that trigger this action
      - http: # creates an API gateway endpoint
          method: POST
          path: /auction/create
  listAuctions: #function
    handler: handler.listAuctions
    description: "Lists existing auctions"
    events: # events that trigger this action
      - http: # creates an API gateway endpoint
          method: GET
          path: /auctions
  getAuction: #function
    handler: handler.getAuction
    description: "get auction provided auction id"
    events: # events that trigger this action
      - http: # creates an API gateway endpoint
          method: GET
          path: /auction/{id}
  placeBid: #function
    handler: handler.placeBid
    description: "places a bid for an auction item"
    events: # events that trigger this action
      - http: # creates an API gateway endpoint
          method: PATCH
          path: /auction/{id}/bid

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

resources:
  Resources:
    AuctionsTable: ${file(./resources/AuctionsTable.yml):AuctionsTableSchemaDefinition}
